const data = [
  {
    id: "backt",
    icon: "iconsminds-air-balloon-1",
    label: "back",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Profile",
    icon: "iconsminds-air-balloon-1",
    label: "Profile",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_about",
    icon: "iconsminds-air-balloon-1",
    label: "About",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_edu",
    icon: "iconsminds-air-balloon-1",
    label: "Education",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Intern",
    icon: "iconsminds-air-balloon-1",
    label: "internships",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_technical",
    icon: "iconsminds-air-balloon-1",
    label: "technical",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_about",
    icon: "iconsminds-air-balloon-1",
    label: "PositionofRes",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_project",
    icon: "iconsminds-air-balloon-1",
    label: "Projects",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_subject",
    icon: "iconsminds-air-balloon-1",
    label: "Subject",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Language",
    icon: "iconsminds-air-balloon-1",
    label: "Language",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Awards",
    icon: "iconsminds-air-balloon-1",
    label: "Awards",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Certification",
    icon: "iconsminds-air-balloon-1",
    label: "Certification",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Competition",
    icon: "iconsminds-air-balloon-1",
    label: "Competition",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Workshop",
    icon: "iconsminds-air-balloon-1",
    label: "Workshop",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_test",
    icon: "iconsminds-air-balloon-1",
    label: "Test Scores",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_patents",
    icon: "iconsminds-air-balloon-1",
    label: "patents",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_publication",
    icon: "iconsminds-air-balloon-1",
    label: "publication",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_scholarship",
    icon: "iconsminds-air-balloon-1",
    label: "scholarship",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_volunteer",
    icon: "iconsminds-air-balloon-1",
    label: "volunteer",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Extra",
    icon: "iconsminds-air-balloon-1",
    label: "Extra",
    to: "/",
    role: "STUDENT",
  },
  {
    id: "student_Social",
    icon: "iconsminds-air-balloon-1",
    label: "Social",
    to: "/",
    role: "STUDENT",
  },
];
export default data;
